### ISSUE TITLE
build-snaps-on-new-release false positive

### ISSUE THREAD

**Issue by battlemidget** [juju-solutions/kubernetes-jenkins#225]
```
Tag v1.12.0-alpha.0 already present
+ rm -rf /tmp/repo2tag
+ cd cdk-addons
+ make KUBE_VERSION=v1.12.0-alpha.0 KUBE_ARCH=amd64
cp -r cdk-addons build
KUBE_VERSION=v1.12.0-alpha.0 KUBE_DASHBOARD_VERSION=v1.8.3 ./get-addon-templates
INFO:__main__:Cloning https://github.com/kubernetes/kubernetes.git with branch v1.12.0-alpha.0
INFO:__main__:Copying addons to /var/lib/jenkins/jobs/build-snaps-on-new-release/workspace/cdk-addons/templates
Traceback (most recent call last):
  File "./get-addon-templates", line 183, in <module>
    main()
  File "./get-addon-templates", line 179, in main
    get_addon_templates()
  File "./get-addon-templates", line 139, in get_addon_templates
    add_addon(repo, "dns/kube-dns/kube-dns.yaml.in", dest + "/kube-dns.yaml")
  File "./get-addon-templates", line 94, in add_addon
    with open(source, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/kubernetesg9alfno7/cluster/addons/dns/kube-dns/kube-dns.yaml.in'
Makefile:9: recipe for target 'default' failed
make: *** [default] Error 1
Credentials cleared.
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: SUCCESS
```

**Comment by battlemidget** [comment]
fixed in latest pipelines
