### ISSUE TITLE
percona-cluster charm fails on s390x and arm64

### ISSUE THREAD

**Issue by hyperbolic2346** [juju-solutions/kubernetes-jenkins#286]
The percona-cluster charm fails to install on s390x and arm64. It is possible it is an issue with the default series of the charm being xenial. It could be something wrong with the charm itself.

```
unit-percona-cluster-0: 20:42:26 ERROR unit.percona-cluster/0.juju-log Bootstrap PXC failed: Command '['systemd-run', '--service-type=forking', 'service', 'mysql', 'bootstrap-pxc']' returned non-zero exit status 1
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed Traceback (most recent call last):
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/config-changed", line 987, in <module>
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed main()
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/config-changed", line 977, in main
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed hooks.execute(sys.argv)
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/core/hookenv.py", line 909, in execute
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed self._hookshook_name
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 93, in _harden_inner2
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed return f(*args, **kwargs)
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/config-changed", line 515, in config_changed
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed bootstrap=not leader_bootstrapped)
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/config-changed", line 259, in render_config_restart_on_changed
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed bootstrap_pxc()
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/percona_utils.py", line 584, in bootstrap_pxc
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed raise Exception(error_msg)
unit-percona-cluster-0: 20:42:26 DEBUG unit.percona-cluster/0.config-changed Exception: Bootstrap PXC failed: Command '['systemd-run', '--service-type=forking', 'service', 'mysql', 'bootstrap-pxc']' returned non-zero exit status 1
```

For reference, this failure was with cs:percona-cluster-272 deployed on xenial.

**Comment by ktsakalozos** [comment]
On arm64 the error is slightly different:
```
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install E: Sub-process /usr/bin/dpkg returned an error code (1)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install Traceback (most recent call last):
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/install.real", line 987, in <module>
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     main()
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/install.real", line 977, in main
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     hooks.execute(sys.argv)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/core/hookenv.py", line 909, in execute
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     self._hooks[hook_name]()
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 93, in _harden_inner2
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     return f(*args, **kwargs)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/install.real", line 182, in install
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     install_percona_xtradb_cluster()
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/install.real", line 163, in install_percona_xtradb_cluster
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     apt_install(determine_packages(), fatal=True)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/fetch/ubuntu.py", line 228, in apt_install
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     _run_apt_command(cmd, fatal)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/fetch/ubuntu.py", line 591, in _run_apt_command
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     retry_message="Couldn't acquire DPKG lock")
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/var/lib/juju/agents/unit-percona-cluster-0/charm/hooks/charmhelpers/fetch/ubuntu.py", line 567, in _run_with_retries
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     result = subprocess.check_call(cmd, **kwargs)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install     raise CalledProcessError(retcode, cmd)
unit-percona-cluster-0: 20:39:53 DEBUG unit.percona-cluster/0.install subprocess.CalledProcessError: Command '['apt-get', '--assume-yes', '--option=Dpkg::Options::=--force-confold', 'install', 'percona-xtradb-cluster-server']' returned non-zero exit status 100
unit-percona-cluster-0: 20:39:53 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
unit-percona-cluster-0: 20:39:53 DEBUG juju.machinelock machine lock released for uniter (run install hook)
unit-percona-cluster-0: 20:39:53 DEBUG juju.worker.uniter.operation lock released
unit-percona-cluster-0: 20:39:53 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-percona-cluster-0: 20:39:53 DEBUG juju.worker.uniter [AGENT-STATUS] error: hook failed: "install"
unit-etcd-2: 20:39:53 DEBUG worker.uniter.jujuc running hook tool "application-version-set"
unit-percona-cluster-0: 20:39:53 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

With:
```
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Job for mysql.service failed because the control process exited with error code. See "systemctl status mysql.service" and "journalctl -xe" for details.
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install invoke-rc.d: initscript mysql, action "start" failed.
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install [0;1;31m●[0m mysql.service - LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install    Loaded: loaded (/etc/init.d/mysql; bad; vendor preset: enabled)
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install    Active: [0;1;31mfailed[0m (Result: exit-code) since Mon 2018-12-03 20:39:49 UTC; 63ms ago
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install      Docs: man:systemd-sysv-generator(8)
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install   Process: 12471 ExecStart=/etc/init.d/mysql start [0;1;31m(code=exited, status=1/FAILURE)[0m
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install 
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:47 juju-8e05a5-13 systemd[1]: Starting LSB: Start and stop the ....
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:47 juju-8e05a5-13 mysql[12471]:  * Starting MySQL (Percona Xtra...d
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:49 juju-8e05a5-13 mysql[12471]:  * The server quit without upda....
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:49 juju-8e05a5-13 mysql[12471]:    ...fail!
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:49 juju-8e05a5-13 systemd[1]: [0;1;39mmysql.service: Control process ex...1[0m
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:50 juju-8e05a5-13 systemd[1]: [0;1;31mFailed to start LSB: Start and st....[0m
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:50 juju-8e05a5-13 systemd[1]: [0;1;39mmysql.service: Unit entered faile....[0m
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Dec 03 20:39:50 juju-8e05a5-13 systemd[1]: [0;1;39mmysql.service: Failed with result....[0m
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Hint: Some lines were ellipsized, use -l to show in full.
unit-etcd-2: 20:39:50 DEBUG worker.uniter.jujuc running hook tool "juju-log"
unit-etcd-2: 20:39:50 INFO unit.etcd/2.juju-log Initializing Snap Layer
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install dpkg: error processing package percona-xtradb-cluster-server-5.6 (--configure):
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install  subprocess installed post-installation script returned error exit status 1
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install dpkg: dependency problems prevent configuration of percona-xtradb-cluster-server:
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install  percona-xtradb-cluster-server depends on percona-xtradb-cluster-server-5.6; however:
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install   Package percona-xtradb-cluster-server-5.6 is not configured yet.
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install 
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install dpkg: error processing package percona-xtradb-cluster-server (--configure):
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install  dependency problems - leaving unconfigured
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install No apport report written because the error message indicates its a followup error from a previous failure.
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install Errors were encountered while processing:
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install  percona-xtradb-cluster-server-5.6
unit-percona-cluster-0: 20:39:50 DEBUG unit.percona-cluster/0.install  percona-xtradb-cluster-server
```

But I was not able to reproduce the above error on arm64. The package is there and deploys fine via the charm. Could this be a transient error?


Here are some deployments of the charm:
```
Model        Controller  Cloud/Region         Version  SLA          Timestamp
test-xenial  localhost   localhost/localhost  2.4.7    unsupported  10:02:07Z

App              Version       Status  Scale  Charm            Store       Rev  OS      Notes 
keystone         13.0.1        error       1  keystone         jujucharms  290  ubuntu     
pc               5.7.20-29.24  active      1  percona-cluster  jujucharms  272  ubuntu     
pcx              5.6.37-26.21  active      1  percona-cluster  jujucharms  272  ubuntu     
percona-cluster  5.6.37-26.21  active      1  percona-cluster  jujucharms  272  ubuntu     

Unit                Workload  Agent  Machine  Public address  Ports     Message
keystone/0*         error     idle   1        10.97.166.135   5000/tcp  hook failed: "shared-db-relation-changed"
pc/0*               active    idle   2        10.97.166.61    3306/tcp  Unit is ready
pcx/0*              active    idle   3        10.97.166.2     3306/tcp  Unit is ready
percona-cluster/0*  active    idle   0        10.97.166.82    3306/tcp  Unit is ready

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.97.166.82   juju-48c7d8-0  xenial      Running
1        started  10.97.166.135  juju-48c7d8-1  bionic      Running
2        started  10.97.166.61   juju-48c7d8-2  bionic      Running
3        started  10.97.166.2    juju-48c7d8-3  xenial      Running
```

```
ubuntu@juju-48c7d8-3:~$ sudo systemctl status mysql.service
● mysql.service - LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon
   Loaded: loaded (/etc/init.d/mysql; bad; vendor preset: enabled)
   Active: active (exited) since Thu 2018-12-06 09:36:11 UTC; 10min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 7539 ExecStop=/etc/init.d/mysql stop (code=exited, status=0/SUCCESS)
  Process: 8207 ExecStart=/etc/init.d/mysql start (code=exited, status=0/SUCCESS)

Dec 06 09:36:10 juju-48c7d8-3 systemd[1]: Starting LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon...
Dec 06 09:36:11 juju-48c7d8-3 mysql[8207]:  * Starting MySQL (Percona XtraDB Cluster) database server mysqld
Dec 06 09:36:11 juju-48c7d8-3 mysql[8207]:    ...done.
Dec 06 09:36:11 juju-48c7d8-3 systemd[1]: Started LSB: Start and stop the mysql (Percona XtraDB Cluster) daemon.
```

**Comment by ktsakalozos** [comment]
On our s390x percona-cluster also deploys fine. Its the keystone and its apt-repository that is giving me a hard time.

**Comment by hyperbolic2346** [comment]
Closing this as it seems it was just a flake of some sort.

**Comment by battlemidget** [comment]
what? the problem still exists in ci, why close this?
